# Generated by Django 3.1.1 on 2020-10-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_greatindia_kalyanday_moonnight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greatindia',
        ),
        migrations.DeleteModel(
            name='jayBharat',
        ),
        migrations.DeleteModel(
            name='Kalyanday',
        ),
        migrations.DeleteModel(
            name='Moonnight',
        ),
    ]
