# Generated by Django 3.1.1 on 2020-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_auto_20201002_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jay_bharat', models.CharField(max_length=100)),
                ('Moon_night', models.CharField(max_length=100)),
                ('Great_India', models.CharField(max_length=100)),
                ('Kalyan_day', models.CharField(max_length=100)),
            ],
        ),
    ]
