# Generated by Django 3.1.1 on 2020-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='chartPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Great_India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jay_bhart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kalyan_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moon_night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
            ],
        ),
    ]
