# Generated by Django 3.1.1 on 2020-10-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_chartpoints_great_india_jay_bhart_kalyan_day_moon_night'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chartPoints',
        ),
        migrations.DeleteModel(
            name='Great_India',
        ),
        migrations.DeleteModel(
            name='jay_bhart',
        ),
        migrations.DeleteModel(
            name='Kalyan_day',
        ),
        migrations.DeleteModel(
            name='Moon_night',
        ),
    ]
