# Generated by Django 3.1.1 on 2020-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201002_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='jay_Bharat_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(max_length=100)),
                ('mun', models.CharField(max_length=100)),
                ('tus', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
            ],
        ),
    ]
