# Generated by Django 3.1.1 on 2020-10-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_great_india_kalyan_day_moon_night'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kalyan_day',
            new_name='Great_India_Chart',
        ),
        migrations.RenameModel(
            old_name='Moon_night',
            new_name='Kalyan_day_Chart',
        ),
        migrations.RenameModel(
            old_name='Great_India',
            new_name='Moon_night_Chart',
        ),
    ]
