# Generated by Django 3.1.1 on 2020-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201002_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='jay_Bharat_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jay_bharat', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='points',
        ),
    ]
