# Generated by Django 3.1.1 on 2020-10-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201002_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jay_bharat_points',
            old_name='Jay_bharat',
            new_name='Jay_bharat_point',
        ),
    ]
