# Generated by Django 3.1.1 on 2020-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20201002_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Great_India_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Great_India_point', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kalyan_day_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kalyan_day_point', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moon_night_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moon_night_point', models.CharField(max_length=100)),
            ],
        ),
    ]
