# Generated by Django 3.1.1 on 2020-10-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_kalyan_day_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Great_India_chart',
        ),
        migrations.DeleteModel(
            name='Jay_bharat_chart',
        ),
        migrations.DeleteModel(
            name='Kalyan_day_chart',
        ),
        migrations.DeleteModel(
            name='Moon_nigh_chart',
        ),
    ]
