# Generated by Django 3.1.1 on 2020-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20201008_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jay_Bharat_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='points',
            name='Great_India',
            field=models.CharField(default='*', max_length=100),
        ),
        migrations.AlterField(
            model_name='points',
            name='Jay_bharat',
            field=models.CharField(default='*', max_length=100),
        ),
        migrations.AlterField(
            model_name='points',
            name='Kalyan_day',
            field=models.CharField(default='*', max_length=100),
        ),
        migrations.AlterField(
            model_name='points',
            name='Moon_night',
            field=models.CharField(default='*', max_length=100),
        ),
    ]
