# Generated by Django 3.1.1 on 2020-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20201008_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='jay_bharat_chart',
            name='Date',
            field=models.CharField(default='*', max_length=100),
        ),
    ]
