# Generated by Django 3.1.1 on 2020-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_jay_bharat_chart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jay_Bharat_panle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
    ]
