# Generated by Django 3.1.1 on 2020-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_jay_bharat_panle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Great_India_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Great_India_panle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kalyan_day_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kalyan_day_panle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moon_night_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moon_night_panle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='*', max_length=100)),
                ('Sun', models.CharField(default='*', max_length=100)),
                ('Mon', models.CharField(default='*', max_length=100)),
                ('Tue', models.CharField(default='*', max_length=100)),
                ('Wed', models.CharField(default='*', max_length=100)),
                ('Thu', models.CharField(default='*', max_length=100)),
                ('Fri', models.CharField(default='*', max_length=100)),
                ('Sat', models.CharField(default='*', max_length=100)),
            ],
        ),
    ]
