# Generated by Django 3.1.1 on 2020-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_great_india_chart_great_india_panle_kalyan_day_chart_kalyan_day_panle_moon_night_chart_moon_night_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalyan_day_chart',
            name='Date',
            field=models.CharField(default='*', max_length=3),
        ),
    ]
