# Generated by Django 3.1.1 on 2020-10-09 03:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20201008_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='jay_bharat_chart',
            name='color',
            field=colorfield.fields.ColorField(default='black', max_length=18),
        ),
    ]
