# Generated by Django 3.1.1 on 2020-10-09 13:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_jay_bharat_chart_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jay_bharat_chart',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
