# Generated by Django 3.1.1 on 2020-10-09 13:05

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20201009_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jay_bharat_chart',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name=models.CharField(default='*', max_length=100)),
        ),
    ]
