# Generated by Django 3.1.1 on 2020-10-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20201009_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jay_bharat_chart',
            name='color',
        ),
    ]
